### ISSUE TITLE
[Question] Publish vs. Notification

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-core-api#104]
I didn't find any explicit definition for the attributes that a Notification needs to have.
My understanding is that a Notification basically is a Publish message which has both a *source*, containing the origin of the message, and a *sink* indicating the target uE of the message. Is this correct?

**Comment by PLeVasseur** [comment]
Not too much documentation that I saw in `up-spec` or `up-core-api`. From what I read, though, those do appear to be the only real requirements I found.

[`up-core-api`'s uattributes.proto](https://github.com/eclipse-uprotocol/up-core-api/blob/db87f2e3bb6e10e64845e05e73cbf145f4d98e12/uprotocol/uattributes.proto#L54-L56)
```protobuf
    // Destination UUri for a message used for unicast message types 
    // (notification, request, response)
    UUri sink = 4;
```

[`UMessageType` would be Publish](https://github.com/eclipse-uprotocol/up-core-api/blob/db87f2e3bb6e10e64845e05e73cbf145f4d98e12/uprotocol/uattributes.proto#L93)
```protobuf
// uProtocol defines message types. Using the message type, validation can be performed to ensure transport
// validity of the data in the {@link UAttributes}.
enum UMessageType {
    UMESSAGE_TYPE_UNSPECIFIED = 0; // Unspecified message type
    UMESSAGE_TYPE_PUBLISH = 1 [(uprotocol.ce_name) = "pub.v1"];    // Publish or notification
    UMESSAGE_TYPE_REQUEST = 2 [(uprotocol.ce_name) = "req.v1"];    // Request 
    UMESSAGE_TYPE_RESPONSE = 3 [(uprotocol.ce_name) = "res.v1"];   // Response
}
```

**Comment by sophokles73** [comment]
Yes, that is what I found as well. And there is the definition of the [mapping to CloudEvent message properties](https://github.com/eclipse-uprotocol/up-spec/blob/ceb40c3e218ba29241f8cc8f10aa141a7a2d3c84/basics/cloudevents.adoc#21-common-attributes) which defines that a Notification's *source* property must contain the producer's topic ...

**Comment by stevenhartley** [comment]
> r

correct

**Comment by sophokles73** [comment]
Ok, thanks for the quick answer :-)
@PLeVasseur I have created https://github.com/eclipse-uprotocol/up-rust/issues/53 to fix the validator accordingly ...
