### ISSUE TITLE
UAttributes integer typed fields

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-core-api#106]
The [UAttributes proto]() contains the following field definitions:

```
// TTL is How long this message should live for after it was generated (in milliseconds).
// Event expires when:
// \$t_current > t_{id} + ttl\$
optional int32 ttl = 6;
    
// Permission level per https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/permissions.adoc[Permissions]
optional int32 permission_level = 7;

// Communication error attribute populated by uP-L2 dispatchers only when an error 
// has occurred in the delivery of RPC request or response events. 
// The contents of this attribute, if present, is the unsigned integer representation of
// UCode
optional int32 commstatus = 8;
```

All of these use type `int32` but none of them can actually contain a negative value, or can they?
Defining these as `uint32` would save us a lot of manual checks in the client libraries ...

**Comment by PLeVasseur** [comment]
Agree with you @sophokles73. For items which are strictly positive it's nicer to have them defined as such in the .proto (especially for languages which are strict about this like Rust!)

**Comment by stevenhartley** [comment]
merged
