### ISSUE TITLE
Definition of response messages

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-core-api#77]
Hi,

I have been going through [usubscription.proto](https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/main/src/main/proto/core/usubscription/v3/usubscription.proto) and [udiscovery.proto](https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/main/src/main/proto/core/udiscovery/v3/udiscovery.proto).

I was very surprise to see that all of the service response messages either *are* `uprotocol.v1.UStatus` or *contain* `uprotocol.v1.UStatus`. This seems to suggest that a client needs to inspect the message content in order to determine if the service invocation was successful or not.

FMPOV this fact would usually be conveyed by means of a feature of the transport protocol being used to convey the message, e.g. an HTTP header field, an MQTT5 property etc. For example, an HTTP status of 200 indicates that the response body contains the current representation of the resource while a status of 400 would indicate a bad request and the response body would contain error details (e.g. encoded as a `uprotocol.v1.UStatus`). 

Is there a particular reason why you want to (re-)define error handling in each and every service definition instead of at the transport protocol binding level?

**Comment by stevenhartley** [comment]
Because we need to separate transport error from service error.  Given that this is a distributed system, I need to know if/when there is a transport (communication) error like timeout for RPC or delivery failures, etc... I also (from an application standpoint) need to get business logic status like the command was accepted correctly or not, I have permission to invoke  the method (or not), etc... 

So communication (transport) failures are in UAttributes.commstatus and the business logic status/states are defined in each uService's Messages.

**Comment by sophokles73** [comment]
> So communication (transport) failures are in UAttributes.commstatus and the business logic status/states are defined in each uService's Messages.

I am not sure if I understand correctly, how the `commstatus` is being used.

Let's make an example:

A client uE wants to invoke a service's method using RPC and one of the intermediary Dispatchers is not able to forward the request message to the service.

My understanding is that the Dispatcher would send a response (on behalf of the target service) with no payload and a *commstatus* of `UNAVAILABLE`, right?

On the other hand, if the request can be delivered successfully to the service but the service implementation determines that a dependent component (e.g. a database connection) is not available, this would result in a message with a *commstatus* of `OK` and a payload that contains the service method's response message which in turn contains a `uprotocol.v1.UStatus` with a *code* of `UNAVAILABLE`, or am I mistaken?

**Comment by stevenhartley** [comment]
commstatus: communication layer errors for RPC method invocation (dispatching errors like timeout, unavailable, etc..).  This dictates how the CompletableFuture<UPayload> is completed (exceptionably or not) so the application can differentiate a communication error from an application layer error. 

Application (business) layer Errors:  Stuffed inside of the request/response messages (i.e. in the UPayload) and is business logic errors (command failed, invalid state for the command, not permitted to invoke the command, etc...).  It can be now either uprotocol.v1.UStatus or google.rpc.Status.

**Comment by sophokles73** [comment]
So my assumptions are correct?

> so the application can differentiate a communication error from an application layer error.

Does this make any difference to a client application? I can imagine that a client might want to use the type of error to determine if it makes sense to try again, e.g. if the client is not authorized then it doesn't make sense to retry, but if the error is (temporarily) unavailable, then it might make sense to try again. However, given that we are using the same error codes/types for both commstatus and response message, I do not see how it makes a difference where the status code has been retrieved from ...

**Comment by sophokles73** [comment]
Then FMPOV the response message definitions should not contain the UStatus but instead should be defined to contain the information returned for a successful invocation only. In the [uProtocol error model definition](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/basics/error_model.adoc) you have already referred to the Google Error Model which FMPOV does exactly what I propose, i.e. service implementations send back either the successful payload *or* an error payload (`google.rpc.Status`) and the client can determine the type of payload to expect from the `commstatus` value in the response message.

**Comment by AnotherDaniel** [comment]
I agree with the notion - this also came up in a review comment on the Rust SDK, where the essence of the discussion can be boiled down to UCode containing an ::Ok value, and what that would mean if UCode is used in a idiomatic Rust-style Result<>.
Also, implementing this Result<> style API did noticeably streamline client code using these functions; so I'm seconding Kai's point.

**Comment by stevenhartley** [comment]
> This also seems to match the way client code invokes operations in e.g. Java, Rust, Python where you get back the _standard_ output variables (without any error/status info) if the invocation succeeds and get back an Exception (Java, Python) or Error object (Rust) when invocation fails.

Totally agree and that is how we've implemented InvokeMethod() for Java that if there is an error in commstatus, we complete the future exceptionally (with the reason why) but if there is no commstatus error, we complete the future with the UPayload. 
Keep in mind that this is unrelated to the return value from send(). Send (from uTransport) is only the ACK (status) for transmitting the message to the next hop. If, for example, the send() fails then you can complete the future returned from InvokeMethod() exceptionally.

**Comment by sophokles73** [comment]
Then I guess there should not be any issue with defining the services' response messages accordingly and remove the `Status` from them ...

**Comment by stevenhartley** [comment]
> that if there is an error in commstatus, we complete the future exceptionally (with the reason why) but if there is no commstatus error, we complete the future with the UPayload.

unless the service needs to report some status code from the RPC, like if you issue the command OpenDoor() and you passed an INVALID_ARGUMENT (want to open a door that doesn't exist)

**Comment by stevenhartley** [comment]
commstatus is Layer 1 or 2 event delivery communication errors and not Layer 3 business logic errors from the service.  If there are no communication errors then commstatus is not populated.

**Comment by sophokles73** [comment]
I understand that this is the *current* way that you have defined it. But it doesn't need to remain that way if we agree that the very same status could be used for all kinds of errors.

Or is there a compelling/convincing argument for why commstatus cannot be used for indicating any kind of error instead of just a communication error?

**Comment by stevenhartley** [comment]
It was to logically separate the different types of errors (L3 vs L1/L2). You're reasoning is the client doesn't care and would treat the types of errors the same correct?

**Comment by sophokles73** [comment]
>  You're reasoning is the client doesn't care and would treat the types of errors the same correct?

At least I currently do not see why a client would/should treat these differently. Did you run into situations in practice where this had to be dealt with differently so far?

**Comment by sophokles73** [comment]
@stevenhartley So, can we remove the `UStatus` from the response message definitions?

**Comment by sophokles73** [comment]
@stevenhartley We need to rectify this issue rather sooner than later. Requiring RPC clients to expect and process a UStatus in the response messages seems awkward and makes them hard to implement.

So can we please remove the `UStatus` from the response message definitions and also clearly define the mechanism of how to return application level errors to a client?

**Comment by stevenhartley** [comment]
@sophokles73 I disagree with removing Status. Services should be able to return whatever they want in their ResponseMessage from a method invocation, be it a complex message, Status, or anything else, we cannot and should not dictate these returned types. Additionally we separated comm status from the application layer status so we could (if the app or services wants) differentiate where the error occurred (in the communication or in the business logic layer)

**Comment by sophokles73** [comment]
I believe that we agree on that a service should be able to define its response message content in any way it wants to. However, I do believe that we should define a mechanism for conveying error information from a server to a client, which will be supported *out-of-the-box* by compliant uProtocol client libraries.

In a [previous comment](https://github.com/eclipse-uprotocol/uprotocol-core-api/issues/77#issuecomment-1830023408), we have established that there already is a definition of how this is supposed to work (currently).
I had then elaborated how an alternative (and much more intuitive) way to do so could look like and had [asked about any reason why that could not be done](https://github.com/eclipse-uprotocol/uprotocol-core-api/issues/77#issuecomment-1852797591).
So far you did not provide an answer to that question so I was wondering what kept us from proceeding on the alternative way which seems to be preferred by [others](https://github.com/eclipse-uprotocol/uprotocol-core-api/issues/77#issuecomment-1847046289) on this thread as well ...

**Comment by stevenhartley** [comment]
@sophokles73  I disagree that handling of the error would be any different w.r.t retry logic. There is a need to differentiate business logic acknowledgement/status from communication status as a method invocation could fail (cannot open the door) vs the request didn't make it to the Door service for various reasons (invalid authority, timeouts, etc...).

**Comment by sophokles73** [comment]
> There is a need to differentiate business logic acknowledgement/status from communication status as a method invocation could fail (cannot open the door) vs the request didn't make it to the Door service for various reasons (invalid authority, timeouts, etc...).

If that is the case, then it would also be possible to use different codes (or ranges) for these in the *commstatus* (which should then probably be renamed to just *status* or something similar generic). For example a code of `1` could indicate a communication problem and `2` could indicate an application error. In both cases, though, the details would be contained in a `UStatus` structure contained in the message payload. Note that the `UStatus` would not need to be extracted from the service's response message in case of an application error.

FMPOV this would would make (generic) error handling much easier and would also better align with the mechanisms used in programming languages.

**Comment by stevenhartley** [comment]
@sophokles73 we want to keep the "layers" clean and separate, business logic in the payload and communication/protocol logic in the UAttributes.

**Comment by sophokles73** [comment]
@PLeVasseur any thoughts on this?

**Comment by PLeVasseur** [comment]
Trying to come up to speed. @sophokles73 -- your point is that when I as a client receive a `UMessage` I need to look at 2 x different things?

1. check the `UMessage.attributes.commstatus` to understand if _there was an issue at the transport layer_
2. following that, then check the `UMessage.payload` to understand if _there was an issue in the business logic_

Is that correct?

**Comment by stevenhartley** [comment]
Absolutely not for 2 above, only the L3 client code does this, not the uPClient or anyone else.

**Comment by PLeVasseur** [comment]
All right, I may be out of my depth here then. I'm not as familiar with a uP-L3 use case. I was thinking that if I'm using e.g. `RpcClient.invokeMethod()`, I'd need to introspect and do 1 & 2 above to check for "good goods".

Seems that's off-base. Not sure if I can contribute w/o a better understanding. Do we have some example of a uP-L3 client code use-case? Might have missed it.

**Comment by stevenhartley** [comment]
checkout up-client-android-java

**Comment by PLeVasseur** [comment]
OK, so for an example of checking commstatus, we'd [look here](https://github.com/eclipse-uprotocol/up-client-android-java/blob/d0a06d974be5eca6e40b79173157e2af581cd4e0/library/src/androidTest/java/org/eclipse/uprotocol/UPClientTest.java#L453-L468)?

And for checking what's returned in the payload (the uP-L3 bit you mentioned?) we'd [look here](https://github.com/eclipse-uprotocol/up-client-android-java/blob/d0a06d974be5eca6e40b79173157e2af581cd4e0/library/src/androidTest/java/org/eclipse/uprotocol/UPClientTest.java#L440-L451)?

**Comment by stevenhartley** [comment]
L3 is outside of uPClient, we do not do anything with errors there.

**Comment by sophokles73** [comment]
Here are some sequence diagrams which illustrate the failure scenarios when invoking an RPC method. I have also added a proposed alternative at the end which FMPOV represents an easier to use and understand approach and which is in line with existing RPC mechanisms like RESTFul services, gRPC and common implementations of RPC invocations via message based infrastructure.

# Current implementation

## Method invocation fails because request cannot be sent

A client wants to invoke a service method via RPC but the transmission of the request message to the broker fails.

```mermaid
sequenceDiagram
  autonumber
  actor C as Client
  participant RPC as RpcClient
  participant UT as MqttTransport
  participant T as MQTT Broker

  C ->>+ RPC: invoke_method()
  Note over C,RPC: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  RPC ->>+ UT: send()
  Note over RPC,UT: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  UT ->>+ T: publish(headers, payload)
  Note over UT,T: headers{type: REQUEST},<br>payload{RequestMessage}
  T -->>- UT: network error
  UT -->>- RPC: Err(UStatus{UNAVAILABLE})
  RPC -->>- C: Err(UStatus{UNAVAILABLE})
```

This is straight forward and the RpcClient can simply forward the UStatus it gets back from the UTransport to the client.

## Method invocation fails because request cannot be delivered

A client wants to invoke a service method via RPC but the forwarding of the request message to the destination device fails.

```mermaid
sequenceDiagram
  autonumber
  actor C as Client
  participant RPC as RpcClient
  participant UT as MqttTransport
  participant S as Streamer

  C ->> RPC: invoke_method()
  Note over C,RPC: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  activate RPC
  RPC ->> UT: send()
  activate UT
  Note over RPC,UT: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  UT ->>+ S: publish(headers, payload)
  Note over UT,S: headers{type: REQUEST},<br>payload{RequestMessage}
  S -->>- UT: message_accepted
  UT -->> RPC: Ok(())
  deactivate UT
  Note over S: Streamer fails to forward<br>message to destination device
  S ->> UT: publish()
  activate UT
  Note over S,UT: headers{commstatus: !OK},<br>payload{UStatus{!OK}}
  UT ->> RPC: Err()
  Note over UT,RPC: UStatus{!OK}
  deactivate UT
  RPC -->> C: Err()
  Note over RPC,C: UStatus{!OK}
  deactivate RPC
```

Again, the RpcClient can simply forward the UStatus it gets back from the UTransport to the client.

**Note** that it is unclear what the value of the *commstatus* property could/should be here, because the [UCodes defined for UStatus](https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/ustatus.proto) do not contain any specific infrastructure error codes.

## Method invocation fails because of application error

A client wants to invoke a service method via RPC. The request messages is delivered to the service implementation but the input parameters are invalid.

```mermaid
sequenceDiagram
  autonumber
  actor C as Client
  participant RPC as RpcClient
  participant UT as MqttTransport
  participant S as Service Impl

  C ->> RPC: invoke_method()
  activate RPC
  Note over C,RPC: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  RPC ->> UT: send()
  activate UT
  Note over RPC,UT: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  UT ->>+ S: publish()
  deactivate UT
  Note over UT,S: headers{type: REQUEST},<br>payload{RequestMessage}
  S ->>- UT: publish()
  activate UT
  Note over S,UT: headers{commstatus: OK},<br>payload{ResponseMessage{<br>UStatus{INVALID_ARGUMENT}}}
  UT ->> RPC: Ok()
  Note over UT,RPC: UAttributes{commstatus: OK},<br>UPayload{ResponseMessage{<br>UStatus{INVALID_ARGUMENT}}}
  deactivate UT
  Note over RPC: parse response<br>and extract status
  RPC -->> C: Err()
  Note over C,RPC: UStatus{INVALID_ARGUMENT}
  deactivate RPC
```

Before returning the result to the client, the RpcClient first checks the *commstatus* of the response message which is `OK` (indicating that there is no transport level problem). However, instead of simply forwarding an `Ok()` result based on the response message, the RpcClient now needs to parse the (service specific) response message and extract the error information from it in order to return an `Err()` result to the client code.

This has the following disadvantages:
1. The RpcClient needs to parse the response message and thus needs to be aware of the response message format.
2. Service implementations are harder to implement because the standard error reporting features of programming languages (Java Exceptions, Rust `Result`) can either not be used at all to report errors, or exceptions need to be *captured* and wrapped into the structure representing a successful outcome. This is both error prone and hard to understand/debug.
3. The response message Protobuf definitions for service methods which do not return any payload cannot simply be defined as the well known [`Empty`](https://protobuf.dev/reference/protobuf/google.protobuf/#empty) message but need to be defined explicitly containing nothing but an optional `UStatus` property.

# Proposed alternative approach

The following sequence diagram illustrates how the third scenario would look like, if the service implementation would return a `UStatus` instead of a `ResponseMessage` in case of an application error. The *commstatus* value could be used to indicate whether the payload contains a `ResponseMessage` (commstatus `OK`), a `UStatus` for a transport level error (e.g. commstatus `TRANSPORT`) or a `UStatus` for for an application error (e.g. commstatus `APPLICATION`). In all of these cases, the RpcClient can simply forward the payload to the client code. All it needs to do is to inspect the commstatus to determine if an `Ok()` or `Err()` result needs to be returned.

```mermaid
sequenceDiagram
  autonumber
  actor C as Client
  participant RPC as RpcClient
  participant UT as MqttTransport
  participant S as Service Impl

  C ->> RPC: invoke_method()
  activate RPC
  Note over C,RPC: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  RPC ->> UT: send()
  activate UT
  Note over RPC,UT: UAttributes{type: REQUEST},<br>UPayload{RequestMessage}
  UT ->>+ S: publish()
  deactivate UT
  Note over UT,S: headers{type: REQUEST},<br>payload{RequestMessage}
  S ->>- UT: publish()
  activate UT
  Note over S,UT: headers{commstatus: APPLICATION},<br>payload{UStatus{INVALID_ARGUMENT}}
  UT ->> RPC: Ok()
  Note over UT,RPC: UAttributes{commstatus: APPLICATION},<br>UPayload{UStatus{INVALID_ARGUMENT}}
  deactivate UT
  RPC -->> C: Err()
  Note over C,RPC: UStatus{INVALID_ARGUMENT}
  deactivate RPC
```

**Comment by stevenhartley** [comment]
@sophokles73  we will talk about this tomorrow but I see the issue. W.r.t _Method invocation fails because of application error_
you're assuming that RpcClient will inspect the uPayload for a UStatus and return it but that is not the case because the only way that could be done is if the RpcClient has the schema of all possible ResponseMessage 's which is not possible as that is part of the contract above RpcClient layer. All that RpcClient returns is protobuf.Message (ResponseMessage) when the future completes successfully (cuz commstatus is OK), or complete future with a failure passing UStatus with the failure from commstatus when there is a communication error occurs.

**Comment by stevenhartley** [comment]
@sophokles73 (et. al.),
Great discussion today on this topic. The approach we took with defining uServices is that Status was explicit in the ResponseMessage as seen in [cabin_climate_service.proto](https://github.com/COVESA/uservices/blob/main/src/main/proto/vehicle/body/cabin_climate/v1/cabin_climate_service.proto) and communication errors in a separate lower layer protocol header commstatus in [uattributes.proto](https://github.com/eclipse-uprotocol/up-core-api/blob/main/uprotocol/uattributes.proto#L75) (and in CloudEvent header). 
The above deviates from various other well known request-response protocols (i.e. HTTP, gRPC, zenoh, etc...) and introduces complicates developers handling of method invocation errors (two ways to get an error). The developers mental model is messed up because invokeMethod() returning OK doesn't mean the method invocation was actually ok. Furthermore, regardless of the failure, all the app cares about is "do I retry or not" based on the specific UCode.

Ideally what is clean and clear for developers for invokeMethod() is:
1. Success: Return ResponseMessage (or empty if nothing to return)
2. Failure: No ResponseMessage but UCode for explicit error reason (comm failure, permission denied, etc...)

After pondering on this all day (and looking at the code), all we need to do is add explicit comm errors in UCode (to not reinvent the wheel) and then change all the service definitions to return nothing or ResponseMessage (without status), services can report errors just like comm errors by completing future in URpcListener.onReceive() with exception (no change to up-client, up-language, etc...)

What is great is we are not forced to change all the services, we could keep it the same but it would be better to change now then when there are 100's of uServices in the wild.

@sophokles73 did all that make sense?

**Comment by sophokles73** [comment]
@stevenhartley You have summed it up correctly and comprehensively :+1: 

Maybe it is worth mentioning that in the failure case of

> Ideally what is clean and clear for developers for invokeMethod() is:
> 
> Success: Return ResponseMessage (or empty if nothing to return)
> Failure: No ResponseMessage but UCode for explicit error reason (comm failure, permission denied, etc...)

I would propose to get back a UStatus, which contains a UCode (or any other well defined code) and may also contain additional information providing context for the error that had orccurred.

**Comment by stevenhartley** [comment]
Thanks @sophokles73. I agree UStatus in lieu of UCode would be better (debated that when I first defined it in our CloudEvent message but thought an int would be simpler). Changing UAttributes is less of an issue (other than breaking backwards compatibility again in core-api). This will break backwards compatibility with our production cloud implementation that is based off 1.3.6 of the protocol (i.e. current CloudEvent message definition).  Given we've reconsidering CloudEvents to the cloud anyways (the message overhead and performance is killing us), we might drop CEs all together.

**Comment by stevenhartley** [comment]
Not sure I'm a fan of changing the response payload though as it changes the contract no?

**Comment by sophokles73** [comment]
> After pondering on this all day (and looking at the code), all we need to do is add explicit comm errors in UCode (to not reinvent the wheel) **and then change all the service definitions to return nothing or ResponseMessage (without status)** ...

Somewhere in the [uProtocol Level 2 Spec](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l2) we need to define that RPC methods can either return the defined ResponseMessage type (in the payload) in conjunction with a *(comm)status* of `OK` to indicate that the invocation was successful, or they can return a `UStatus` (in the payload) in conjunction with a *(comm)status* of `APP_ERROR` to indicate that the invocation was erroneous.

For existing service definitions we could still keep their response message definitions as is because the original behavior for a failed method invocation would still work, i.e. the client code would get back a `UMessage` that contains the ResponseMessage with the embedded UStatus ...

**Comment by frankghe** [comment]
I am coming late to this thread, but I am surprised that there is an intent to merge protocol status with functional status. HTTP was reminded as an example. This is a good example, showing a separation between protocol (http) status and content status (included in the payload). For example, status=200 indicates that http request/response completed successfully. But it says nothing about the actual functional content (e.g. the response might include a 'fail' status).
The following http definition summarizes it well: "A response header is an [HTTP header](https://developer.mozilla.org/en-US/docs/Glossary/HTTP_header) that can be used in an HTTP response and that doesn't relate to the content of the message."
(reference: https://developer.mozilla.org/en-US/docs/Glossary/Response_header)

**Comment by sophokles73** [comment]
> For example, status=200 indicates that http request/response completed successfully. But it says nothing about the actual functional content (e.g. the response might include a 'fail' status).

and an HTTP status of 400 is usually used to indicate that parameters passed in with the request (payload) could not be processed by the server-side application handling the request.

> This is a good example, showing a separation between protocol (http) status and content status (included in the payload).

I agree to the extent that the details regarding *which input parameters could not be processed and why* are being conveyed in the response *payload* (as opposed to the headers). The status code, however, is always used to indicate whether the request has been processed successfully (2xx) or not (4xx -> client error, 5xx -> server error). A client can always use this status code to determine how the response payload needs to be processed/interpreted.

We are proposing to do exactly this, convey status in a response *attribute/header* but always convey error details in the response *payload*. The only change we are making is to not convey application error details within the same message struture that is being returned in case of a successful invocation.

**Comment by tamarafischer** [comment]
A little late to the party. I read the entire thread. Here is my point of view or humble opinion.

I like the Rust Result monad, is it a true monad? not sure but I like the idea of pure functions. Java has them as well, you just needed to write it yourself. Personally for my streaming apps I have a ProceedOrSkip object.

I don't like the idea of an RPC call returning more than one thing:
- I hated the Javascript code that had to be written to read the HTTP status and then parse the payload in **2 different ways**. I know this is how it is done in communication networks, but please don't tell me it is being nice to the developer on the other side.
- I hated Java exceptions, or functions that had an API that lied, or basically again, me as a developer having to deal with a function communicating in more than one way - exception handling and happy path which is the declared API.

I find the idea of a pure function returning what it declares it will return very appealing.

That said, I understand the networking systems - they don't know the payload and hence, if HTTP or MQTT has a problem, they can't return the problem payload since they are not aware of it! Hence the layers that @stevenhartley is talking about.
In addition, having a wrapper such as ResponseMessage that wraps an embedded UStatus that wraps something else is also a tradeoff on performance.
Unwrapping means deserializing and I keep hearing from the embedded developers that the serialization and deserialization is killing them and hogging the precious CPU cycles.
Another thing is dependencies - if all uServices now need to return the ResponseMessage wrapper/monad then it is a dependency. Just defining it in proto does not really help, I need something helpful for composition and this is language dependent so an interface would make me happy.

I would like to suggest we take all the great options of architecture from the thread and understand the tradeoffs and optimizations needed.

Doing Domain Driven Design, uService designers should be able to define their RPC domain in their proto files. This is the contract of the service. If a uService wants to return an object that provides a success or a failure, like the Rust Result or my ProceedOrSkip or any other data model, that would be amazing. I am not sure we should make everyone implement their code this way.

Client libraries can help but the ideas should be clean and clear even without the need for client libraries. My opinion - don't shoot.

**Comment by sophokles73** [comment]
@stevenhartley have you been able to clarify with other stakeholders? FMPOV we need to come to a conclusion here rather sooner than later. The outcome of this should also be reflected in the change made to commstatus in https://github.com/eclipse-uprotocol/up-core-api/pull/107.

**Comment by stevenhartley** [comment]
Others agreed to the idea in principle but without having to change commstatus as there are already 200 vs 300 vs 400 level errors. I'm not sure if we need to add any more per say unless we want to differentiate a TIMEOUT from application layer or comm layer, WDYT?

**Comment by stevenhartley** [comment]
Closing this issue as the project will be archived and we will move the topic to up-spec project
